name: Publish CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd ./library && ./gradlew publish
      env:
        GPR_USER: ${{ secrets.GITHUB_ACTOR }}
        GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
